# Generated by Django 2.2 on 2019-04-28 16:42

from django.db import migrations, models
import django.db.models.deletion
import recurrence.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Presenter',
            fields=[
                ('id', models.BigIntegerField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('photo', models.ImageField(blank=True, upload_to='presenters/')),
                ('cover_art', models.ImageField(blank=True, upload_to='presenters/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'radio_presenters',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigIntegerField(editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=30)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('artwork', models.ImageField(blank=True, upload_to='uploads/')),
                ('featured', models.BooleanField(default=False)),
                ('recurrences', recurrence.fields.RecurrenceField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('presenter', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='programs', to='radio.Presenter')),
            ],
            options={
                'db_table': 'radio_programs',
                'ordering': ['-created_at'],
            },
        ),
    ]
