# Generated by Django 2.2 on 2019-04-28 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='artwork',
            field=models.ImageField(blank=True, upload_to='uploads/programs/'),
        ),
    ]
