# Generated by Django 2.2 on 2019-04-30 15:01

from django.db import migrations, models
import django.utils.timezone
import luzeiros.radio.models.helpers.music


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0003_auto_20190430_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='release_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='track',
            name='preview_file',
            field=models.FileField(blank=True, upload_to=luzeiros.radio.models.helpers.music.path_for_track),
        ),
    ]
